artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.zip # download data as zip
  unzip_dir: artifacts/data_ingestion #unziping data will be stored in this paht
